/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Diamond.gltf 
Author: Kugatsu Tsukai 3D Models Hub (https://sketchfab.com/KugatsuT)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-diamond-free-giveaway-618d614891354c1f86f07845080e13e7
Title: Blue Diamond - Free Giveaway
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Diamond.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 1.5, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DiamondOutside} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Diamond.gltf')
